### PR TITLE
Changed jquery requirement to > 1.9.x in bower.json

### PR DESCRIPTION
**Pull request by hugoj-goncalves**
As per https://plugins.jquery.com/bootstrap-maxlength/
JQuery needed should be > 1.9

### CODE REVIEW

**Comment by mimo84** [comment]
Thank you :)

**Comment by hugoj-goncalves** [comment]
Glad to help ;)

**Comment by hugoj-goncalves** [comment]
If we could have a new release with this modification would be helpful for those using bower to install dependencies ( just a sugestion tough ;p )

**Comment by mimo84** [comment]
I am planning to do rewrite some of the functionalities in a better way
very soon :)

**Pull request merged**
