### PR TITLE
IE crash fix

### PR DESCRIPTION
**Pull request by svhouten1**
IE sometimes crashes if 'maxLengthIndicator' is not there. (on init only)

Error: Unable to get property 'html' of undefined or null reference

### CODE REVIEW

**Comment by vincentjames501** [comment]
+1. Please merge this. I can reproduce this in all browsers when using in conjunction with Angularjs.

**Comment by mimo84** [comment]
I am sorry but this is breaking the build. I can't merge it in until that is fixed.

**Comment by vincentjames501** [comment]
#99 should be mergeable once travis runs

**Comment by mimo84** [comment]
Merged with #99

**Pull request closed without merging**
